### ISSUE TITLE
Error in running manage.py

### ISSUE THREAD

**Issue by dustin-lind** [mikeizbicki/cmc-csci143#116]
Hi @mikeizbicki,

I'm following the instructions from _Dockerizing Flask with Postgres, Gunicorn, and Nginx_ article.

I ran the following commands:
```
$ mkdir flask-on-docker && cd flask-on-docker
$ mkdir services && cd services
$ mkdir web && cd web
$ mkdir project
$ python3.9 -m venv env
$ source env/bin/activate
(env)$ pip install flask==1.1.2
```

And created the `__init__.py` and the `manage.py` files exactly like the instructions specified.

Now when I run:
```
(env)$ export FLASK_APP=project/__init__.py
(env)$ python manage.py run
```

I get the following error:

```
 * Serving Flask app "project/__init__.py"
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    cli()
  File "/home/Dustin.Lind.22/flask-on-docker/services/web/env/lib/python3.6/s                                                                                ite-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/Dustin.Lind.22/flask-on-docker/services/web/env/lib/python3.6/s                                                                                ite-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/Dustin.Lind.22/flask-on-docker/services/web/env/lib/python3.6/s                                                                                ite-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/Dustin.Lind.22/flask-on-docker/services/web/env/lib/python3.6/s                                                                                ite-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/Dustin.Lind.22/flask-on-docker/services/web/env/lib/python3.6/s                                                                                ite-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/Dustin.Lind.22/flask-on-docker/services/web/env/lib/python3.6/s                                                                                ite-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/Dustin.Lind.22/flask-on-docker/services/web/env/lib/python3.6/s                                                                                ite-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/Dustin.Lind.22/flask-on-docker/services/web/env/lib/python3.6/s                                                                                ite-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/Dustin.Lind.22/flask-on-docker/services/web/env/lib/python3.6/s                                                                                ite-packages/flask/cli.py", line 860, in run_command
    extra_files=extra_files,
  File "/home/Dustin.Lind.22/flask-on-docker/services/web/env/lib/python3.6/s                                                                                ite-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/home/Dustin.Lind.22/flask-on-docker/services/web/env/lib/python3.6/s                                                                                ite-packages/werkzeug/serving.py", line 959, in inner
    fd=fd,
  File "/home/Dustin.Lind.22/flask-on-docker/services/web/env/lib/python3.6/s                                                                                ite-packages/werkzeug/serving.py", line 783, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/Dustin.Lind.22/flask-on-docker/services/web/env/lib/python3.6/s                                                                                ite-packages/werkzeug/serving.py", line 688, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "/usr/lib/python3.6/socketserver.py", line 456, in __init__
    self.server_bind()
  File "/usr/lib/python3.6/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.6/socketserver.py", line 470, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

This is my port forwarding configuration in Putty because the instructions say to navigate to `http://localhost:5000/` after running the above commands.
![image](https://user-images.githubusercontent.com/78048849/152259912-accfa79f-a3af-409a-9c55-051ff1837e10.png)

I wish I knew how to interpret this error, but it is a little over my head. Do you have any suggestions?

-Dustin

**Comment by Tonnpo** [comment]
I believe that the default port being used is 5000. So, in my case, I specified port by running
```
python manage.py -p ${UID}
```

**Comment by dustin-lind** [comment]
Hey @Tonnpo! Thanks for trying to help!

When I ran
```
python3 manage.py -p ${UID}
```
This time I get the error
```
Traceback (most recent call last):
  File "manage.py", line 1, in <module>
    from flask.cli import FlaskGroup
ModuleNotFoundError: No module named 'flask'
```
For other people who may experience this problem, I went ahead and ran
```
pip3 install flask
```
Things are working now!

-Dustin
