### ISSUE TITLE
Cannot access directory

### ISSUE THREAD

**Issue by dabalus** [mikeizbicki/cmc-csci143#143]
I am working on the twitter coronavirus problem set and when run command below 

```
./src/map.py --input_path=/data-fast/twitter\ 2020/geoTwitter20-02-16.zip
```

I get the following error: 

```
'r20-02-16.zip
Traceback (most recent call last):
  File "./src/map.py", line 42, in <module>
    with zipfile.ZipFile(args.input_path) as archive:
  File "/usr/lib/python3.6/zipfile.py", line 1113, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/data-fast/twitter 2020/geoTwitter20-02-16.zip'
```

**Comment by Bhargavaa1** [comment]
I believe the command to process the zip file for an individual day should be
```
./src/map.py --input_path=/data/tweets_corona/geoTwitter20-02-16.zip
```
