### ISSUE TITLE
Getting error after trying to pip install package

### ISSUE THREAD

**Issue by yurynamgung** [mikeizbicki/cmc-csci143#145]
I was following along with the class lectures and copied the code we went over into docker-compose.yml, load_tweets.sh, and load_tweets.py. After doing this, I ran ```docker-compose up -d``` and ```sh load_tweets.sh```. The second command gave me some import errors (the sqlalchemy module was not found) so I tried running ```pip install sqlalchemy```. However, running the pip install command seems to have caused some problems. Now I am getting significantly more errors when I try to run ```sh load_tweets.sh```

The following is the error message I get:
```
load normalized
2022-03-10 21:02:37.942248 test-data.zip
Traceback (most recent call last):
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1809, in _execute_context
    cursor, statement, parameters, context
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedFunction: operator does not exist: text = bigint
LINE 4:     WHERE id_tweets = 1245138808045264898
                            ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "load_tweets.py", line 294, in <module>
    insert_tweet(connection,tweet)
  File "load_tweets.py", line 99, in insert_tweet
    'id_tweets':tweet['id'],
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1295, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1497, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1852, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2033, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1809, in _execute_context
    cursor, statement, parameters, context
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) operator does not exist: text = bigint
LINE 4:     WHERE id_tweets = 1245138808045264898
                            ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.

[SQL: 
    SELECT id_tweets 
    FROM tweets
    WHERE id_tweets = %(id_tweets)s
    ]
[parameters: {'id_tweets': 1245138808045264898}]
(Background on this error at: https://sqlalche.me/e/14/f405)
Command exited with non-zero status 1
0.35user 0.05system 0:00.43elapsed 94%CPU (0avgtext+0avgdata 43028maxresident)k
0inputs+0outputs (0major+13547minor)pagefaults 0swaps
load denormalized
Command terminated by signal 13
0.00user 0.00system 0:00.00elapsed 100%CPU (0avgtext+0avgdata 3152maxresident)k
0inputs+0outputs (0major+330minor)pagefaults 0swaps
ERROR:  relation "tweets_jsonb" does not exist
```

I wasn't sure how to fix this problem. Removing the container, volumes, and exiting out of the lambda server doesn't seem to fix the errors for me or bring things to how they were before I ran pip install

**Comment by mikeizbicki** [comment]
Great question.

`psycopg2` is the name of the library that sqlalchemy uses to interact with postgres.  So anytime you see an error message that contains it, you should be looking for sql errors.  In your case, the key lines are
```
psycopg2.errors.UndefinedFunction: operator does not exist: text = bigint
LINE 4:     WHERE id_tweets = 1245138808045264898
                            ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
```
Reading this, we can see you have a sql error (not a python error) on line 4 of your sql.  In particular, `id_tweets` is a `TEXT` column in postgres (equivalent of a `str` in python), and you are comparing that to a number.  This needs to be compared to another `TEXT` type.  Probably you are storing the `id_tweets` as an `int` in python, and you should cast this to a `str` before passing it to sqlalchemy.

**Comment by yurynamgung** [comment]
thank you! casting the id_tweets as a string fixed the error. Do you know what is causing the last line of the error above ```ERROR:  relation "tweets_jsonb" does not exist```?

After copying the "create/update the user table" query from our lecture, I continued to get this error when loading the denormalized table.

I also got errors saying that the users table did not exist; would we have to check for this error and create a users table through sqlalchemy or is there another script we can run to create all the tables based on the schema files?

Here is the complete error I was getting:
```
load normalized
2022-03-14 21:07:17.580138 test-data.zip
Traceback (most recent call last):
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1809, in _execute_context
    cursor, statement, parameters, context
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "users" does not exist
LINE 2:         INSERT INTO users
                            ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "load_tweets.py", line 313, in <module>
    insert_tweet(connection,tweet)
  File "load_tweets.py", line 139, in insert_tweet
    'withheld_in_countries':tweet['user'].get('withheld_in_countries', None),})
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1295, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1497, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1852, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2033, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1809, in _execute_context
    cursor, statement, parameters, context
  File "/home/ynamgung/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "users" does not exist
LINE 2:         INSERT INTO users
                            ^

[SQL: 
        INSERT INTO users
        (id_users,created_at,updated_at,screen_name,name,location,id_urls,description,protected,verified,friends_count,listed_count,favourites_count,statuses_count,withheld_in_countries)
        VALUES
        (%(id_users)s,%(created_at)s,%(updated_at)s,%(screen_name)s,%(name)s,%(location)s,%(id_urls)s,%(description)s,%(protected)s,%(verified)s,%(friends_count)s,%(listed_count)s,%(favourites_count)s,%(statuses_count)s,%(withheld_in_countries)s)
        ON CONFLICT (id_users) DO NOTHING
                ]
[parameters: {'id_users': 145676658, 'created_at': 'Wed May 19 15:51:18 +0000 2010', 'updated_at': 'Wed Apr 01 00:00:00 +0000 2020', 'screen_name': 'Marlenetica', 'name': 'Marlene Hernández A', 'location': 'Moravia, San José,  Costa Rica', 'id_urls': None, 'description': 'Mujer, madre, abuela, tica y un poco loca. \n/ReTweet', 'protected': False, 'verified': False, 'friends_count': 5056, 'listed_count': 134, 'favourites_count': 169588, 'statuses_count': 348283, 'withheld_in_countries': None}]
(Background on this error at: https://sqlalche.me/e/14/f405)
Command exited with non-zero status 1
0.37user 0.07system 0:00.45elapsed 96%CPU (0avgtext+0avgdata 43436maxresident)k
0inputs+0outputs (0major+13521minor)pagefaults 0swaps
load denormalized
ERROR:  relation "tweets_jsonb" does not exist
Command terminated by signal 13
0.00user 0.00system 0:00.09elapsed 7%CPU (0avgtext+0avgdata 3204maxresident)k
0inputs+0outputs (0major+333minor)pagefaults 0swaps
```

**Comment by mikeizbicki** [comment]
You probably have your inserts backwards.  That is, you are getting the error
```
psycopg2.errors.UndefinedTable: relation "users" does not exist
```
because you are using python on the denormalized database.  And the error
```
ERROR:  relation "tweets_jsonb" does not exist
```
because you are using the `COPY` command on the normalized database.

**Comment by yurynamgung** [comment]
Would that be in the ```load_tweets.sh``` file? I copied what was shown during our lecture and had the following in the contents of my file, which seems to be the correct order for the python and ```COPY``` commands as below:

```
# but we will write are code so that we can easily load an arbitrary number of files
files='
test-data.zip
'

echo 'load normalized'
for file in $files; do
    # call the load_tweets.py file to load data into pg_normalized
    time python3 -u load_tweets.py --db=postgresql://postgres:pass@localhost:12398/ "--inputs=$file"
done

echo 'load denormalized'
for file in $files; do
    # use SQL's COPY command to load data into pg_denormalized
    time unzip -p "$file" | sed 's/\\u0000//g' | psql postgresql://postgres:pass@localhost:10100/ -c "COPY tweets_jsonb (data) FROM STDIN csv quote e'\x01' delimiter e'\x02';"
done
```

I also didn't touch anything in the ```load_tweets.py``` file before getting the error
```
ERROR:  relation "tweets_jsonb" does not exist
```

**Comment by yurynamgung** [comment]
I realized I had switched the port order around in the ```load_tweets.sh``` file and the ```docker-compose.yml``` file. Thank you!
