### ISSUE TITLE
psycopg2.errors.UndefinedColumn: column "url" of relation "users" does not exist

### ISSUE THREAD

**Issue by joeybodoia** [mikeizbicki/cmc-csci143#155]
Hey everyone,

After making the necessary modifications to `services/pg_normalized_batch/schema.sql`, as well as `load_tweets_batch.py`, I run into the following issue when I run `sh load_tweets_sequential.sh` or `sh load_tweets_parallel.sh`:

```
================================================================================
load pg_normalized_batch
================================================================================
NOTICE:  identifier "load_tweets.py --inputs data/geoTwitter21-01-01.zip data/geoTwitter21-01-02.zip data/geoTwitter21-01-03.zip data/geoTwitter21-01-04.zip data/geoTwitter21-01-05.zip data/geoTwitter21-01-06.zip data/geoTwitter21-01-07.zip data/geoTwitter21-01-08.zip data/geoTwitter21-01-09.zip data/geoTwitter21-01-10.zip" will be truncated to "load_tweets.py --inputs data/geoTwitter21-01-01.zip data/geoTwi"
2022-04-01 15:24:45.247310 data/geoTwitter21-01-10.zip
2022-04-01 15:24:46.266753 insert_tweets i= 0
Traceback (most recent call last):
  File "/home/Joseph.Bodoia.21/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1809, in _execute_context
    cursor, statement, parameters, context
  File "/home/Joseph.Bodoia.21/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column "url" of relation "users" does not exist
LINE 1: ...ount,verified,updated_at,created_at,location,name,url,descri...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "load_tweets_batch.py", line 459, in <module>
    insert_tweets(connection,tweets,args.batch_size)
  File "load_tweets_batch.py", line 175, in insert_tweets
    _insert_tweets(connection, tweet_batch)
  File "load_tweets_batch.py", line 398, in _insert_tweets
    bulk_insert(connection, 'users', users)
  File "load_tweets_batch.py", line 156, in bulk_insert
    res = connection.execute(sqlalchemy.sql.text(sql), binds)
  File "/home/Joseph.Bodoia.21/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1295, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/Joseph.Bodoia.21/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 326, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/Joseph.Bodoia.21/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1497, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/Joseph.Bodoia.21/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1852, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/Joseph.Bodoia.21/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2033, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/Joseph.Bodoia.21/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/home/Joseph.Bodoia.21/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1809, in _execute_context
    cursor, statement, parameters, context
  File "/home/Joseph.Bodoia.21/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column "url" of relation "users" does not exist
LINE 1: ...ount,verified,updated_at,created_at,location,name,url,descri...
```

This issue, particularly the line 
```
psycopg2.errors.UndefinedColumn: column "url" of relation "users" does not exist
LINE 1: ...ount,verified,updated_at,created_at,location,name,url,descri...
```
seems to suggest that there is no `url` column in the users table, however, in `services/pg_normalized_batch/schema.sql`, I clearly have a `url` column:
`services/pg_normalized_batch/schema.sql`:
```
CREATE TABLE users (
    id_users BIGINT,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    url TEXT,
    friends_count INTEGER,
    listed_count INTEGER,
    favourites_count INTEGER,
    statuses_count INTEGER,
    protected BOOLEAN,
    verified BOOLEAN,
    screen_name TEXT,
    name TEXT,
    location TEXT,
    description TEXT,
    withheld_in_countries VARCHAR(2)[]
);
```

Also, I have bring running `docker-compose down` and `docker volume prune` between each run of `sh load_tweets_sequential.sh` or  `sh load_tweets_parallel.sh`, so I don't think anything related to volumes is involved in the issue.

Has anybody else encountered a similar issue?

**Comment by mikeizbicki** [comment]
If you open up psql and run the command
```
# \d users
```
I think you'll see that you don't in fact have a `url` column.  Most likely, you are still using an old version of the schema in your database construction for some reason.  My best guess as to the cause is that you either forgot to delete an old volume or you forgot to rebuild the container after making changes to the `schema.sql` file.

**Comment by mikeizbicki** [comment]
Reading your last paragraph a bit more carefully, I see that you do mention pruning the volumes, but you don't mention rebuilding the containers, so I'm guessing that's the culprit.  Without rebuilding, the container will use the old `schema.sql` file when constructing the database.

**Comment by joeybodoia** [comment]
You're right, not rebuilding the containers was the culprit. Thanks for the help, Mike.
