### ISSUE TITLE
Docker Build Permission

### ISSUE THREAD

**Issue by choughton21** [mikeizbicki/cmc-csci143#17]
Hello,

I have followed the instructions on https://runnable.com/docker/python/dockerize-your-flask-application but when it comes to the section running the image, when I try to do the command ```docker build -t flask-tutorial:latest .``` it says permission denied while trying to connect to the Docker daemon.

**Comment by mikeizbicki** [comment]
Without the full error message, it's hard to say exactly what the problem is.  The `DOCKER_HOST` and the `PATH` environment variables and the `chmod` command (among many other things) can all cause permissions issues.  Can you reply with the full error message?

**Comment by choughton21** [comment]
Hello, yes, here it is.

```
free(): invalid pointer
SIGABRT: abort
PC=0x7f8a56ec1f47 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc4200a7cc0, 0xc4200a7ce8)
        /usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc4200a7c90 sp=0xc4200a7c50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x1680270)
        github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc4200a7cc0 sp=0xc4200a7c90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x1680270)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc4200a7cf8 sp=0xc4200a7cc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc420016360)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc4200a7da0 sp=0xc4200a7cf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc4200a7e88, 0x410022, 0xc4200162b0)
        <autogenerated>:4 +0x46 fp=0xc4200a7de0 sp=0xc4200a7da0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc4200a7e68 sp=0xc4200a7de0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7ffd4f75761e, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc4200a7ed8 sp=0xc4200a7e68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc4200a7f58 sp=0xc4200a7ed8
main.main()
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc4200a7f88 sp=0xc4200a7f58
runtime.main()
        /usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc4200a7fe0 sp=0xc4200a7f88
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4200a7fe8 sp=0xc4200a7fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1

rax    0x0
rbx    0x7ffd4f755f90
rcx    0x7f8a56ec1f47
rdx    0x0
rdi    0x2
rsi    0x7ffd4f755d20
rbp    0x7ffd4f756090
rsp    0x7ffd4f755d20
r8     0x0
r9     0x7ffd4f755d20
r10    0x8
r11    0x246
r12    0x7ffd4f755f90
r13    0x1000
r14    0x0
r15    0x30
rip    0x7f8a56ec1f47
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=flask-tutorial%3Alatest&target=&ulimits=null&version=1: dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by mikeizbicki** [comment]
```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock
```
This indicates that the `DOCKER_HOST` environment variable is set incorrectly.  Running
```
export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock
```
should fix the problem.
