### ISSUE TITLE
Error downloading warc files

### ISSUE THREAD

**Issue by DestrosCMC** [mikeizbicki/cmc-csci143#217]
I am still having an issue downloading warc files, which may be related to the fact that when I try to download them, a new container is spun up and everything is redownloaded. I have made the changes recommended to the Dockerfiles in #209 and tried the solution in #213 but it just deletes the already built (duplicate) container for the downloader. I can attach my Dockerfiles if that could help provide clarity.

**Comment by DestrosCMC** [comment]
Now my logs are displaying this error. Does this mean that my url is incorrect?

```
2022-05-09 20:10:09:INFO:pspacy:valid_langs=['af', 'ar', 'bg', 'bn', 'ca', 'cs', 'da', 'de', 'el', 'en', 'es', 'et', 'eu', 'fa', 'fi', 'fr', 'ga', 'gu', 'he', 'hi', 'hr', 'hu', 'hy', 'id', 'is', 'it', 'ja', 'kn', 'ko', 'lb', 'lij', 'lt', 'lv', 'ml', 'mr', 'nb', 'ne', 'nl', 'pl', 'pt', 'ro', 'ru', 'si', 'sk', 'sl', 'sq', 'sr', 'sv', 'ta', 'te', 'th', 'tl', 'tr', 'tt', 'uk', 'ur', 'vi', 'xx', 'yo', 'zh']
2022-05-09 20:10:09:INFO:pspacy:initializing xx
2022-05-09 20:10:09:INFO:root:downloading url https://data.commoncrawl.org/CC-MAIN-2016-40/warc.paths.gz to /tmp/tmp01gh3ezr
Traceback (most recent call last):
  File "/tmp/metahtml/downloader_warc.py", line 188, in <module>
    process_warc_from_url(connection,args.warc)
  File "/tmp/metahtml/downloader_warc.py", line 70, in process_warc_from_url
    warc_path = wget.download(warc_url, out=tempdir)
  File "/usr/local/lib/python3.9/dist-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/lib/python3.9/urllib/request.py", line 239, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

**Comment by mikeizbicki** [comment]
I believe #218 will resolve this issue.
