### ISSUE TITLE
sqlalchemy.exc.StatementError: A value is required for bind parameter 

### ISSUE THREAD

**Issue by jaymaliye** [mikeizbicki/cmc-csci143#313]
I am getting the following error on github workflows. Any help?

> ```
> sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'created_at'
> [SQL: 
>             INSERT INTO users
>             (id_users, created_at, updated_at, screen_name, name, location, id_urls, description, protected, verified, friends_count, listed_count, favourites_count, statuses_count, withheld_in_countries)
>             VALUES
>             (%(id_users)s, %(created_at)s, %(updated_at)s, %(screen_name)s, %(name)s, %(location)s, %(id_urls)s, %(description)s, %(protected)s, %(verified)s, %(friends_count)s, %(listed_count)s, %(favourites_count)s, %(statuses_count)s, %(withheld_in_countries)s)
>             ON CONFLICT DO NOTHING
>             ]
> [parameters: [{'id_users': None}]]
> (Background on this error at: https://sqlalche.me/e/20/cd3x)
> Command exited with non-zero status 1
> ```

**Comment by tennisoctocat** [comment]
It looks like you need to add `created_at`, `updated_at`, etc. into your parameters list since right now your parameters are only `{'id_users': None}`.  So you probably want to have your parameters be `{'id_users': None, 'created_at': <something>, 'updated_at':<something>, ... '}`

**Comment by jaymaliye** [comment]
I have added all the variables to the parameters list. It looks like this:

```
res = connection.execute(sql, {
            'id_users': tweet['user']['id'],
            'created_at': tweet['user'].get('created_at', None),
            ... 
            'withheld_in_countries': tweet['user'].get('withheld_in_countries', None),
            })
```

**Comment by tennisoctocat** [comment]
Ah okay, I'm not sure then, sorry!

**Comment by koffqq** [comment]
I have the same issue. Please let me know if anyone figures this out!

```
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'id_tweets'
[SQL: 
            INSERT INTO tweet_media
                (id_tweets, id_urls, type)
            VALUES
                (%(id_tweets)s, %(id_urls)s, %(type)s)
            ON CONFLICT DO NOTHING
                ]
[parameters: [{'id_tweet': 1245138808112394243, 'id_urls': 1, 'type': 'video'}]]
(Background on this error at: https://sqlalche.me/e/20/cd3x)
Command exited with non-zero status 1
```

**Comment by mikeizbicki** [comment]
@koffqq You can see in the error message:
```
[parameters: [{'id_tweet': 1245138808112394243, 'id_urls': 1, 'type': 'video'}]]
```
so you've provided the parameter `id_tweet`, but the first line of the error is
```
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'id_tweets'
```
asking for parameter `id_tweets`, which you have not provided.

@jaymaliye The error is showing that you've only the parameter `id_users`:
```
[parameters: [{'id_users': None}]]
```
So somehow you are calling the `execute` function incorrectly that is causing the other parameters to get discarded.

**Comment by jaymaliye** [comment]
@mikeizbicki given the code:

```
res = connection.execute(sql, {
            'id_users': tweet['user']['id'],
            'created_at': tweet['user'].get('created_at', None),
            ... 
            'withheld_in_countries': tweet['user'].get('withheld_in_countries', None),
            })
```

Do you know what might be wrong? I can't seem to figure it out. If possible, can I stop by your office?

**Comment by mikeizbicki** [comment]
@jaymaliye I'm skeptical, though, that what you posted here really matches the code in your python file.  In particular, I'm pretty sure the `...` isn't in your python file, and so this code has been edited in some way from what's in your python file, and there's no way for me to know if those edits are related to this error.

Sorry, I'm not on campus today so I can't meet.  But I can help you through github here if you: 
1. post the full output of running your command (start with the line that you enter in the terminal and copy and paste all the way until the end)
2. post the entirety of your `sql` variable and `execute` function call, including line numbers from the original file.

In general when posting error messages like this, you always want to include all of the information I listed above and not abbreviated versions.

**Comment by jaymaliye** [comment]
@mikeizbicki I added the ellipsis because I thought the error was in the first few lines. That's my bad. I have included 1 and 2 from your comment above below.

1. Output of commands:
- LAMBDA SERVER: for some reason load_tweets.sh was not working on the lambda server, so I was testing my code on Workflows (this also might have been an issue). I have not touched the first few lines of code in the load_tweets.py file. So I'm not sure why it's not importing. 
  - This is what I get when I run `$ sh load_tweets.sh`
```
load normalized
Traceback (most recent call last):
  File "load_tweets.py", line 4, in <module>
    import sqlalchemy
ModuleNotFoundError: No module named 'sqlalchemy'
Command exited with non-zero status 1
0.12user 0.02system 0:00.14elapsed 99%CPU (0avgtext+0avgdata 23960maxresident)k
0inputs+0outputs (0major+3373minor)pagefaults 0swaps
load denormalized
COPY 9998
```
    

- WORKFLOWS:
  - This is what I get when I commit my file to GitHub:
```
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'created_at'
[SQL: 
            INSERT INTO users
            (id_users, created_at, updated_at, screen_name, name, location, id_urls, description, protected, verified, friends_count, listed_count, favourites_count, statuses_count, withheld_in_countries)
            VALUES
            (%(id_users)s, %(created_at)s, %(updated_at)s, %(screen_name)s, %(name)s, %(location)s, %(id_urls)s, %(description)s, %(protected)s, %(verified)s, %(friends_count)s, %(listed_count)s, %(favourites_count)s, %(statuses_count)s, %(withheld_in_countries)s)
            ON CONFLICT DO NOTHING
            ]
[parameters: [{'id_users': None}]]
(Background on this error at: https://sqlalche.me/e/20/cd3x)
Command exited with non-zero status 1
```

2. SQL variable and execute call:
```
sql = sqlalchemy.sql.text('''
            INSERT INTO users
            (id_users, created_at, updated_at, screen_name, name, location, id_urls, description, protected, verified, friends_count, listed_count, favourites_count, statuses_count, withheld_in_countries)
            VALUES
            (:id_users, :created_at, :updated_at, :screen_name, :name, :location, :id_urls, :description, :protected, :verified, :friends_count, :listed_count, :favourites_count, :statuses_count, :withheld_in_countries)
            ON CONFLICT DO NOTHING
            ''')

        res = connection.execute(sql, {
            'id_users': tweet['user']['id'],
            'created_at': tweet['user']['created_at'],
            'updated_at': tweet['created_at'],
            'screen_name': remove_nulls(tweet['user']['screen_name']),
            'name': remove_nulls(tweet['user']['name']),
            'location': remove_nulls(tweet['user']['location']),
            'id_urls': user_id_urls,
            'description': remove_nulls(tweet['user']['description']),
            'protected': tweet['user']['protected'],
            'verified': tweet['user']['verified'],
            'friends_count': tweet['user']['friends_count'],
            'listed_count': tweet['user']['listed_count'],
            'favourites_count': tweet['user']['favourites_count'],
            'statuses_count': tweet['user']['statuses_count'], 
            'withheld_in_countries': tweet['user'].get('withheld_in_countries', None),
            })
```

**Comment by mikeizbicki** [comment]
First, when you get an error like
```
ModuleNotFoundError: No module named 'sqlalchemy'
```
you can resolve the error by installing the module with `pip`.  Running
```
$ pip3 install sqlalchemy
```
on the lambda server will resolve this problem.  We've had to do this several times already during the semester for other libraries.

---

Second, YOU DIDN'T PROVIDE THE INFORMATION I ASKED FOR IN YOUR ERROR REPORTS!!!!  In particular, you did not provide the full error message, and you did not provide the line numbers of your python code.  I took a look at your github actions, and the full error is
```
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
    context = constructor(
  File "/home/runner/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1185, in _init_compiled
    self.compiled_parameters = [
  File "/home/runner/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1186, in <listcomp>
    compiled.construct_params(
  File "/home/runner/.local/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 1722, in construct_params
    raise exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: A value is required for bind parameter 'created_at' (Background on this error at: https://sqlalche.me/e/20/cd3x)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/twitter_postgres/twitter_postgres/load_tweets.py", line 454, in <module>
    insert_tweet(connection,tweet)
  File "/home/runner/work/twitter_postgres/twitter_postgres/load_tweets.py", line 207, in insert_tweet
    res = connection.execute(sql,{
  File "/home/runner/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/home/runner/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/runner/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/runner/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1814, in _execute_context
    self._handle_dbapi_exception(
  File "/home/runner/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/runner/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1808, in _execute_context
    context = constructor(
  File "/home/runner/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1185, in _init_compiled
    self.compiled_parameters = [
  File "/home/runner/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1186, in <listcomp>
    compiled.construct_params(
  File "/home/runner/.local/lib/python3.10/site-packages/sqlalchemy/sql/compiler.py", line 1722, in construct_params
    raise exc.InvalidRequestError(
sqlalchemy.exc.StatementError: (sqlalchemy.exc.InvalidRequestError) A value is required for bind parameter 'created_at'
[SQL: 
            INSERT INTO users
            (id_users, created_at, updated_at, screen_name, name, location, id_urls, description, protected, verified, friends_count, listed_count, favourites_count, statuses_count, withheld_in_countries)
            VALUES
            (%(id_users)s, %(created_at)s, %(updated_at)s, %(screen_name)s, %(name)s, %(location)s, %(id_urls)s, %(description)s, %(protected)s, %(verified)s, %(friends_count)s, %(listed_count)s, %(favourites_count)s, %(statuses_count)s, %(withheld_in_countries)s)
            ON CONFLICT DO NOTHING
            ]
[parameters: [{'id_users': None}]]
(Background on this error at: https://sqlalche.me/e/20/cd3x)
Command exited with non-zero status 1
```
This is an admittedly daunting error message, but python provides these long errors because all that information is useful for debugging.  You should always report the entire error message when you are asking for help (either from me or anyone else online).  From this traceback, we can see that the error happens on line 207 in `load_tweets.py`.  But this is not the code that you were pasting to github (which was line 116-140).  Again, the reason I asked you to provide line numbers in the code you paste is so that we can match them up with the error messages.  It's frustrating to me that you are asking for help and not providing me with the information I requested, making me do extra work of digging through your github account.

Looking at your actual code on github, the problem is that line 207 has improper indentation and so you are calling an `execute` function with the wrong `sql` variable.  Changing the indentation should fix this problem.

**Comment by jaymaliye** [comment]
@mikeizbicki I'm sorry I did not read the instructions clearly. I apologize for this and it won't happen again. 

I know it's probably the last thing you want to do right now, but I fixed the indentation and have another issue. I have formatted it the correct way this time (and I'll be sure to do this every time)

1. post the full output of running your command (start with the line that you enter in the terminal and copy and paste all the way until the end)
  - Terminal Command: `$ sh load_tweets.sh`
  - Output:
```
load normalized
2023-03-29 15:00:20.488948 test-data.zip
2023-03-29 15:00:20.495156 test-data.zip example.jsonl i= 0 id= 1245138808045264898
Traceback (most recent call last):
  File "/home/Jayaditya.Maliye.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/Jayaditya.Maliye.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ForeignKeyViolation: insert or update on table "tweet_tags" violates foreign key constraint "tweet_tags_id_tweets_fkey"
DETAIL:  Key (id_tweets)=(1245138808112394243) is not present in table "tweets".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "load_tweets.py", line 386, in <module>
    insert_tweet(connection,tweet)
  File "load_tweets.py", line 325, in insert_tweet
    'tag': tag
  File "/home/Jayaditya.Maliye.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1380, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/Jayaditya.Maliye.23/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 335, in _execute_on_connection
    self, multiparams, params, execution_options
  File "/home/Jayaditya.Maliye.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_clauseelement
    cache_hit=cache_hit,
  File "/home/Jayaditya.Maliye.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1944, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/Jayaditya.Maliye.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2125, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/Jayaditya.Maliye.23/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/Jayaditya.Maliye.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1901, in _execute_context
    cursor, statement, parameters, context
  File "/home/Jayaditya.Maliye.23/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.ForeignKeyViolation) insert or update on table "tweet_tags" violates foreign key constraint "tweet_tags_id_tweets_fkey"
DETAIL:  Key (id_tweets)=(1245138808112394243) is not present in table "tweets".

[SQL: 
                INSERT INTO tweet_tags
                (id_tweets,tag)
                VALUES
                (%(id_tweets)s,%(tag)s)
                ON CONFLICT DO NOTHING
                ]
[parameters: {'id_tweets': 1245138808112394243, 'tag': '#coronavirusdeutschland'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
load denormalized
COPY 9998
```
2. post the entirety of your sql variable and execute function call, including line numbers from the original file.
```
302         ########################################
303         # insert into the tweet_tags table
304         ########################################
305 
306         try:
307             hashtags = tweet['extended_tweet']['entities']['hashtags']
308             cashtags = tweet['extended_tweet']['entities']['symbols']
309         except KeyError:
310             hashtags = tweet['entities']['hashtags']
311             cashtags = tweet['entities']['symbols']
312 
313         tags = [ '#'+hashtag['text'] for hashtag in hashtags ] + [ '$'+cashtag['text'] for cashtag in cashtags ]
314 
315         for tag in tags:
316             sql=sqlalchemy.sql.text('''
317                 INSERT INTO tweet_tags
318                 (id_tweets,tag)
319                 VALUES
320                 (:id_tweets,:tag)
321                 ON CONFLICT DO NOTHING
322                 ''')
323             res =  connection.execute(sql, {
324                 'id_tweets':tweet['id'],
325                 'tag': tag
326                 })
```

Once again, I'm very sorry for not following the instructions correctly.

**Comment by jaymaliye** [comment]
@mikeizbicki I started from scratch and got it to work. Thanks for your help. Once again, sorry for messing up the error comment.
